server.port=8081
spring.application.name=complaignts-service

#spring.datasource.url=jdbc:mysql://projectservices.mysql.database.azure.com:3306/datascheme?useSSL=true&requireSSL=true&trustServerCertificate=true
#spring.datasource.username = lj9
#spring.datasource.password=LaJa2556
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:h2:mem:complaintsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=complaints
spring.datasource.password=complaints

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console